2017-10-06 13:27:14,930 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 13:29:27,062 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 13:34:46,910 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 13:37:17,322 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 13:37:34,345 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 13:38:39,877 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 13:38:55,710 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 13:39:11,174 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 13:39:35,836 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 13:40:19,898 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 13:42:08,089 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 13:42:37,131 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 13:44:50,418 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 13:48:24,408 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 13:48:44,470 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 14:01:29,563 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 14:01:48,483 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 14:03:28,792 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 14:03:45,023 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 14:08:03,191 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 14:08:14,273 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 14:09:50,016 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 14:10:12,499 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 14:10:44,296 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 14:11:44,924 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 14:15:06,634 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 14:16:27,983 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 14:17:08,823 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 14:17:41,755 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 14:23:35,296 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 14:24:21,092 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 14:25:01,375 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 14:25:20,158 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 14:27:12,016 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 14:27:28,528 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 14:29:19,855 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 14:29:48,020 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 14:34:51,914 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 14:38:20,190 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 15:00:22,319 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 15:07:27,448 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 15:08:18,746 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 15:09:53,694 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 15:10:57,164 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 15:11:30,467 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 15:12:40,029 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 15:15:16,476 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 15:21:24,085 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 15:21:53,141 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 15:23:58,069 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 15:31:08,773 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 15:32:29,467 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 15:32:57,750 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 15:33:45,782 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 15:35:18,039 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 15:43:22,240 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 15:46:47,197 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 15:47:11,956 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 15:48:36,740 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 15:50:51,766 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 15:55:10,943 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 15:55:36,772 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 15:56:28,813 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 15:57:36,092 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 15:58:37,834 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 15:59:26,944 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 16:00:58,872 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 16:01:17,490 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 16:02:06,756 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 16:02:54,546 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 16:03:47,286 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 16:04:06,292 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 16:05:20,753 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 16:09:03,164 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 16:09:25,259 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 16:10:47,719 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 16:10:57,230 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 16:11:05,619 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 16:11:27,019 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 16:11:41,318 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 16:12:08,408 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 16:12:10,526 [ERROR] [Holzworth] Holzworth fails to open.
Traceback (most recent call last):
  File "C:/Users/jgou/PycharmProjects/mmt-autobench/autobench/inst/pn_machine.py", line 145, in __init__
    self.holzworth = visa.ResourceManager().open_resource("TCPIP0::%s::9760::SOCKET" % tcpip_addr)
  File "C:\Users\jgou\AppData\Local\Continuum\Anaconda2\lib\site-packages\pyvisa\highlevel.py", line 1644, in open_resource
    res.open(access_mode, open_timeout)
  File "C:\Users\jgou\AppData\Local\Continuum\Anaconda2\lib\site-packages\pyvisa\resources\resource.py", line 203, in open
    self.session, status = self._resource_manager.open_bare_resource(self._resource_name, access_mode, open_timeout)
  File "C:\Users\jgou\AppData\Local\Continuum\Anaconda2\lib\site-packages\pyvisa\highlevel.py", line 1601, in open_bare_resource
    return self.visalib.open(self.session, resource_name, access_mode, open_timeout)
  File "C:\Users\jgou\AppData\Local\Continuum\Anaconda2\lib\site-packages\pyvisa\ctwrapper\functions.py", line 1211, in open
    ret = library.viOpen(session, resource_name, access_mode, open_timeout, byref(out_session))
  File "C:\Users\jgou\AppData\Local\Continuum\Anaconda2\lib\site-packages\pyvisa\ctwrapper\highlevel.py", line 188, in _return_handler
    raise errors.VisaIOError(ret_value)
VisaIOError: VI_ERROR_RSRC_NFOUND (-1073807343): Insufficient location information or the requested device or resource is not present in the system.
2017-10-06 16:12:27,214 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 16:13:05,188 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 16:13:24,763 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 16:13:45,253 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 16:14:17,176 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 16:15:31,576 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 16:15:56,061 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 16:19:45,562 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 16:23:33,321 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 16:26:50,801 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 16:32:50,349 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 16:32:59,861 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 16:38:06,384 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 16:39:05,648 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 16:46:08,263 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 16:46:57,622 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 16:49:55,092 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 16:50:16,069 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 16:50:33,698 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 16:56:54,385 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 16:59:41,558 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 17:00:39,963 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 17:01:17,614 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 17:01:56,709 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 17:02:41,569 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 17:07:01,625 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 17:12:01,786 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 17:24:05,516 [ERROR] [Holzworth] Holzworth fails to open.
Traceback (most recent call last):
  File "C:/Users/jgou/PycharmProjects/mmt-autobench/autobench/inst/pn_machine.py", line 146, in __init__
    self.holzworth = visa.ResourceManager().open_resource("TCPIP0::%s::9760::SOCKET" % tcpip_addr)
  File "C:\Users\jgou\AppData\Local\Continuum\Anaconda2\lib\site-packages\pyvisa\highlevel.py", line 1644, in open_resource
    res.open(access_mode, open_timeout)
  File "C:\Users\jgou\AppData\Local\Continuum\Anaconda2\lib\site-packages\pyvisa\resources\resource.py", line 203, in open
    self.session, status = self._resource_manager.open_bare_resource(self._resource_name, access_mode, open_timeout)
  File "C:\Users\jgou\AppData\Local\Continuum\Anaconda2\lib\site-packages\pyvisa\highlevel.py", line 1601, in open_bare_resource
    return self.visalib.open(self.session, resource_name, access_mode, open_timeout)
  File "C:\Users\jgou\AppData\Local\Continuum\Anaconda2\lib\site-packages\pyvisa\ctwrapper\functions.py", line 1211, in open
    ret = library.viOpen(session, resource_name, access_mode, open_timeout, byref(out_session))
  File "C:\Users\jgou\AppData\Local\Continuum\Anaconda2\lib\site-packages\pyvisa\ctwrapper\highlevel.py", line 188, in _return_handler
    raise errors.VisaIOError(ret_value)
VisaIOError: VI_ERROR_RSRC_NFOUND (-1073807343): Insufficient location information or the requested device or resource is not present in the system.
2017-10-06 17:24:34,813 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 17:27:17,196 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 17:27:36,872 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 17:27:49,891 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 17:33:57,845 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 17:34:17,706 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 17:40:45,223 [ERROR] [Holzworth] Holzworth fails to open.
Traceback (most recent call last):
  File "C:/Users/jgou/PycharmProjects/mmt-autobench/autobench/inst/pn_machine.py", line 146, in __init__
    self.holzworth = visa.ResourceManager().open_resource("TCPIP0::%s::9760::SOCKET" % tcpip_addr)
  File "C:\Users\jgou\AppData\Local\Continuum\Anaconda2\lib\site-packages\pyvisa\highlevel.py", line 1644, in open_resource
    res.open(access_mode, open_timeout)
  File "C:\Users\jgou\AppData\Local\Continuum\Anaconda2\lib\site-packages\pyvisa\resources\resource.py", line 203, in open
    self.session, status = self._resource_manager.open_bare_resource(self._resource_name, access_mode, open_timeout)
  File "C:\Users\jgou\AppData\Local\Continuum\Anaconda2\lib\site-packages\pyvisa\highlevel.py", line 1601, in open_bare_resource
    return self.visalib.open(self.session, resource_name, access_mode, open_timeout)
  File "C:\Users\jgou\AppData\Local\Continuum\Anaconda2\lib\site-packages\pyvisa\ctwrapper\functions.py", line 1211, in open
    ret = library.viOpen(session, resource_name, access_mode, open_timeout, byref(out_session))
  File "C:\Users\jgou\AppData\Local\Continuum\Anaconda2\lib\site-packages\pyvisa\ctwrapper\highlevel.py", line 188, in _return_handler
    raise errors.VisaIOError(ret_value)
VisaIOError: VI_ERROR_RSRC_NFOUND (-1073807343): Insufficient location information or the requested device or resource is not present in the system.
2017-10-06 17:41:05,308 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 17:43:02,709 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 17:44:16,052 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 18:00:18,493 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 18:16:14,259 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 18:18:48,835 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-06 18:19:00,841 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-10 18:00:22,273 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-10 18:02:20,407 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-10 18:02:52,596 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-10 18:03:08,862 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-10 18:07:40,596 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-13 17:24:52,191 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-13 17:25:10,793 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-13 17:25:32,937 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-13 17:25:48,746 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-13 17:26:16,279 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-13 17:28:17,473 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-13 17:30:29,739 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-13 17:32:17,398 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-13 17:33:17,346 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-13 17:37:55,841 [ERROR] [Holzworth] Holzworth fails to open.
Traceback (most recent call last):
  File "C:/Users/jgou/PycharmProjects/mmt-autobench/autobench/inst/pn_machine.py", line 146, in __init__
    self.holzworth = visa.ResourceManager().open_resource("TCPIP0::%s::9760::SOCKET" % tcpip_addr)
  File "C:\Users\jgou\AppData\Local\Continuum\Anaconda2\lib\site-packages\pyvisa\highlevel.py", line 1644, in open_resource
    res.open(access_mode, open_timeout)
  File "C:\Users\jgou\AppData\Local\Continuum\Anaconda2\lib\site-packages\pyvisa\resources\resource.py", line 203, in open
    self.session, status = self._resource_manager.open_bare_resource(self._resource_name, access_mode, open_timeout)
  File "C:\Users\jgou\AppData\Local\Continuum\Anaconda2\lib\site-packages\pyvisa\highlevel.py", line 1601, in open_bare_resource
    return self.visalib.open(self.session, resource_name, access_mode, open_timeout)
  File "C:\Users\jgou\AppData\Local\Continuum\Anaconda2\lib\site-packages\pyvisa\ctwrapper\functions.py", line 1211, in open
    ret = library.viOpen(session, resource_name, access_mode, open_timeout, byref(out_session))
  File "C:\Users\jgou\AppData\Local\Continuum\Anaconda2\lib\site-packages\pyvisa\ctwrapper\highlevel.py", line 188, in _return_handler
    raise errors.VisaIOError(ret_value)
VisaIOError: VI_ERROR_RSRC_NFOUND (-1073807343): Insufficient location information or the requested device or resource is not present in the system.
2017-10-13 17:38:05,131 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-13 17:38:07,371 [ERROR] [Holzworth] Holzworth fails to open.
Traceback (most recent call last):
  File "C:/Users/jgou/PycharmProjects/mmt-autobench/autobench/inst/pn_machine.py", line 146, in __init__
    self.holzworth = visa.ResourceManager().open_resource("TCPIP0::%s::9760::SOCKET" % tcpip_addr)
  File "C:\Users\jgou\AppData\Local\Continuum\Anaconda2\lib\site-packages\pyvisa\highlevel.py", line 1644, in open_resource
    res.open(access_mode, open_timeout)
  File "C:\Users\jgou\AppData\Local\Continuum\Anaconda2\lib\site-packages\pyvisa\resources\resource.py", line 203, in open
    self.session, status = self._resource_manager.open_bare_resource(self._resource_name, access_mode, open_timeout)
  File "C:\Users\jgou\AppData\Local\Continuum\Anaconda2\lib\site-packages\pyvisa\highlevel.py", line 1601, in open_bare_resource
    return self.visalib.open(self.session, resource_name, access_mode, open_timeout)
  File "C:\Users\jgou\AppData\Local\Continuum\Anaconda2\lib\site-packages\pyvisa\ctwrapper\functions.py", line 1211, in open
    ret = library.viOpen(session, resource_name, access_mode, open_timeout, byref(out_session))
  File "C:\Users\jgou\AppData\Local\Continuum\Anaconda2\lib\site-packages\pyvisa\ctwrapper\highlevel.py", line 188, in _return_handler
    raise errors.VisaIOError(ret_value)
VisaIOError: VI_ERROR_RSRC_NFOUND (-1073807343): Insufficient location information or the requested device or resource is not present in the system.
2017-10-13 17:38:31,825 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-13 17:48:43,394 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-13 17:48:55,665 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-13 17:49:19,655 [ERROR] [Holzworth] Holzworth fails to open.
Traceback (most recent call last):
  File "C:/Users/jgou/PycharmProjects/mmt-autobench/autobench/inst/pn_machine.py", line 146, in __init__
    self.holzworth = visa.ResourceManager().open_resource("TCPIP0::%s::9760::SOCKET" % tcpip_addr)
  File "C:\Users\jgou\AppData\Local\Continuum\Anaconda2\lib\site-packages\pyvisa\highlevel.py", line 1644, in open_resource
    res.open(access_mode, open_timeout)
  File "C:\Users\jgou\AppData\Local\Continuum\Anaconda2\lib\site-packages\pyvisa\resources\resource.py", line 203, in open
    self.session, status = self._resource_manager.open_bare_resource(self._resource_name, access_mode, open_timeout)
  File "C:\Users\jgou\AppData\Local\Continuum\Anaconda2\lib\site-packages\pyvisa\highlevel.py", line 1601, in open_bare_resource
    return self.visalib.open(self.session, resource_name, access_mode, open_timeout)
  File "C:\Users\jgou\AppData\Local\Continuum\Anaconda2\lib\site-packages\pyvisa\ctwrapper\functions.py", line 1211, in open
    ret = library.viOpen(session, resource_name, access_mode, open_timeout, byref(out_session))
  File "C:\Users\jgou\AppData\Local\Continuum\Anaconda2\lib\site-packages\pyvisa\ctwrapper\highlevel.py", line 188, in _return_handler
    raise errors.VisaIOError(ret_value)
VisaIOError: VI_ERROR_RSRC_NFOUND (-1073807343): Insufficient location information or the requested device or resource is not present in the system.
2017-10-13 17:49:31,055 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-13 17:49:49,790 [INFO] [Holzworth] Holzworth opens successfully.
2017-10-13 17:50:05,444 [INFO] [Holzworth] Holzworth opens successfully.
2017-11-03 17:39:41,434 [ERROR] [Holzworth] Holzworth fails to open.
Traceback (most recent call last):
  File "C:/Users/jgou/PycharmProjects/mmt-autobench/autobench/inst/pn_machine.py", line 146, in __init__
    self.holzworth = visa.ResourceManager().open_resource("TCPIP0::%s::9760::SOCKET" % tcpip_addr)
  File "C:\Users\jgou\AppData\Local\Continuum\Anaconda2\lib\site-packages\pyvisa\highlevel.py", line 1644, in open_resource
    res.open(access_mode, open_timeout)
  File "C:\Users\jgou\AppData\Local\Continuum\Anaconda2\lib\site-packages\pyvisa\resources\resource.py", line 203, in open
    self.session, status = self._resource_manager.open_bare_resource(self._resource_name, access_mode, open_timeout)
  File "C:\Users\jgou\AppData\Local\Continuum\Anaconda2\lib\site-packages\pyvisa\highlevel.py", line 1601, in open_bare_resource
    return self.visalib.open(self.session, resource_name, access_mode, open_timeout)
  File "C:\Users\jgou\AppData\Local\Continuum\Anaconda2\lib\site-packages\pyvisa\ctwrapper\functions.py", line 1211, in open
    ret = library.viOpen(session, resource_name, access_mode, open_timeout, byref(out_session))
  File "C:\Users\jgou\AppData\Local\Continuum\Anaconda2\lib\site-packages\pyvisa\ctwrapper\highlevel.py", line 188, in _return_handler
    raise errors.VisaIOError(ret_value)
VisaIOError: VI_ERROR_RSRC_NFOUND (-1073807343): Insufficient location information or the requested device or resource is not present in the system.
2017-11-03 17:43:09,589 [INFO] [Holzworth] Holzworth opens successfully.
2017-11-03 17:45:57,674 [INFO] [Holzworth] Holzworth opens successfully.
2017-11-03 17:51:15,204 [INFO] [Holzworth] Holzworth opens successfully.
2017-11-13 10:33:29,724 [INFO] [Holzworth] Holzworth opens successfully.
2017-11-13 10:34:36,757 [INFO] [Holzworth] Holzworth opens successfully.
2017-11-13 10:35:04,101 [INFO] [Holzworth] Holzworth opens successfully.
2017-11-13 10:35:37,252 [INFO] [Holzworth] Holzworth opens successfully.
2017-11-13 10:39:03,959 [INFO] [Holzworth] Holzworth opens successfully.
2017-11-13 11:00:24,302 [INFO] [Holzworth] Holzworth opens successfully.
2017-11-13 11:03:01,529 [INFO] [Holzworth] Holzworth opens successfully.
2017-11-13 11:28:39,479 [INFO] [Holzworth] Holzworth opens successfully.
2017-12-06 11:50:50,069 [ERROR] [Holzworth] Holzworth fails to open.
Traceback (most recent call last):
  File "C:/Users/jgou/PycharmProjects/mmt-autobench/autobench/inst/pn_machine.py", line 147, in __init__
    self.holzworth = visa.ResourceManager().open_resource("TCPIP0::%s::9760::SOCKET" % tcpip_addr)
  File "C:\Users\jgou\AppData\Local\Continuum\Anaconda2\lib\site-packages\pyvisa\highlevel.py", line 1644, in open_resource
    res.open(access_mode, open_timeout)
  File "C:\Users\jgou\AppData\Local\Continuum\Anaconda2\lib\site-packages\pyvisa\resources\resource.py", line 203, in open
    self.session, status = self._resource_manager.open_bare_resource(self._resource_name, access_mode, open_timeout)
  File "C:\Users\jgou\AppData\Local\Continuum\Anaconda2\lib\site-packages\pyvisa\highlevel.py", line 1601, in open_bare_resource
    return self.visalib.open(self.session, resource_name, access_mode, open_timeout)
  File "C:\Users\jgou\AppData\Local\Continuum\Anaconda2\lib\site-packages\pyvisa\ctwrapper\functions.py", line 1211, in open
    ret = library.viOpen(session, resource_name, access_mode, open_timeout, byref(out_session))
  File "C:\Users\jgou\AppData\Local\Continuum\Anaconda2\lib\site-packages\pyvisa\ctwrapper\highlevel.py", line 188, in _return_handler
    raise errors.VisaIOError(ret_value)
VisaIOError: VI_ERROR_RSRC_NFOUND (-1073807343): Insufficient location information or the requested device or resource is not present in the system.
2017-12-06 11:53:17,381 [INFO] [Holzworth] Holzworth opens successfully.
2017-12-06 14:34:35,201 [INFO] [Holzworth] Holzworth opens successfully.
2017-12-06 14:36:54,512 [INFO] [Holzworth] Holzworth opens successfully.
2017-12-06 14:38:33,931 [INFO] [Holzworth] Holzworth opens successfully.
2017-12-06 14:38:48,961 [INFO] [Holzworth] Holzworth opens successfully.
2018-01-24 16:30:35,855 [ERROR] [Holzworth] Holzworth fails to open.
Traceback (most recent call last):
  File "C:/Users/jgou/PycharmProjects/mmt-autobench/autobench/inst/pn_machine.py", line 147, in __init__
    self.holzworth = visa.ResourceManager().open_resource("TCPIP0::%s::9760::SOCKET" % tcpip_addr)
  File "C:\Users\jgou\AppData\Local\Continuum\Anaconda2\lib\site-packages\pyvisa\highlevel.py", line 1644, in open_resource
    res.open(access_mode, open_timeout)
  File "C:\Users\jgou\AppData\Local\Continuum\Anaconda2\lib\site-packages\pyvisa\resources\resource.py", line 203, in open
    self.session, status = self._resource_manager.open_bare_resource(self._resource_name, access_mode, open_timeout)
  File "C:\Users\jgou\AppData\Local\Continuum\Anaconda2\lib\site-packages\pyvisa\highlevel.py", line 1601, in open_bare_resource
    return self.visalib.open(self.session, resource_name, access_mode, open_timeout)
  File "C:\Users\jgou\AppData\Local\Continuum\Anaconda2\lib\site-packages\pyvisa\ctwrapper\functions.py", line 1211, in open
    ret = library.viOpen(session, resource_name, access_mode, open_timeout, byref(out_session))
  File "C:\Users\jgou\AppData\Local\Continuum\Anaconda2\lib\site-packages\pyvisa\ctwrapper\highlevel.py", line 188, in _return_handler
    raise errors.VisaIOError(ret_value)
VisaIOError: VI_ERROR_RSRC_NFOUND (-1073807343): Insufficient location information or the requested device or resource is not present in the system.
2018-01-24 16:31:44,869 [INFO] [Holzworth] Holzworth opens successfully.
2018-01-24 16:32:15,749 [INFO] [Holzworth] Holzworth opens successfully.
2018-01-24 16:32:42,618 [INFO] [Holzworth] Holzworth opens successfully.
